# https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose/blob/master/2-containers/compose-v3/labels/docker-compose.yaml

version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - "${PWD}/vhost.d:/etc/nginx/vhost.d"
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    networks:
      - otswebnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
    depends_on:
      - nginx-proxy
    volumes:
      - "${PWD}/vhost.d:/etc/nginx/vhost.d"
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - otswebnet

  ots-explorer:
    image: ots-explorer
    environment:
      - "VIRTUAL_PROTO=http"
      - "VIRTUAL_HOST=<DOMAIN_LE>"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=<DOMAIN_LE>"
      - "LETSENCRYPT_EMAIL=<EMAIL_LE>"
    restart: always
    networks:
      - otswebnet

volumes:
  conf:
  html:
  dhparam:
  certs:

networks:
  otswebnet:
    external: true
